export type Home = {
  slug: string;
  name: string;
  brand: string;
  series: string;
  beds: number;
  baths: number;
  sqft: string;
  tags: string[];
  price: string;
  photo?: { src: string; alt: string };
};

export const homes: Home[] = [
  {
    slug: "the-dolly",
    name: "The Dolly",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8785E",
    beds: 3,
    baths: 2,
    sqft: "1,178",
    tags: ["Single Wide", "By Order"],
    price: "94,900",
  },
  {
    slug: "pike",
    name: "Pike",
    brand: "Champion Homes",
    series: "Champion Homes Tiny Home",
    beds: 1,
    baths: 1,
    sqft: "546",
    tags: ["Tiny Home", "Arriving"],
    price: "50,000",
    photo: { src: "/homes/pike.jpg", alt: "Pike - Tiny Home manufactured home by Champion Homes" },
  },
  {
    slug: "oak-ridge",
    name: "Oak Ridge",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8978",
    beds: 4,
    baths: 2,
    sqft: "2,280",
    tags: ["Triple Wide", "By Order"],
    price: "167,999",
    photo: { src: "/homes/oak-ridge.jpg", alt: "Oak Ridge - Triple Wide manufactured home by Skyline Homes" },
  },
  {
    slug: "the-serenity",
    name: "The Serenity",
    brand: "Skyline Homes",
    series: "Skyline Homes Embrace 2864H42A7C",
    beds: 4,
    baths: 2,
    sqft: "1,707",
    tags: ["Double Wide", "By Order"],
    price: "115,000",
    photo: { src: "/homes/the-serenity.jpg", alt: "The Serenity - Double Wide manufactured home by Skyline Homes" },
  },
  {
    slug: "the-osborne",
    name: "The Osborne",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8855",
    beds: 3,
    baths: 2,
    sqft: "1,386",
    tags: ["Double Wide", "By Order"],
    price: "118,000",
    photo: { src: "/homes/the-osborne.jpg", alt: "The Osborne - Double Wide manufactured home by Skyline Homes" },
  },
  {
    slug: "the-johnny",
    name: "The Johnny",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8703",
    beds: 3,
    baths: 2,
    sqft: "1,116",
    tags: ["Single Wide", "By Order"],
    price: "92,000",
    photo: { src: "/homes/the-johnny.jpg", alt: "The Johnny - Single Wide manufactured home by Skyline Homes" },
  },
  {
    slug: "the-george",
    name: "The George",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8761AJ",
    beds: 2,
    baths: 2,
    sqft: "879",
    tags: ["Single Wide", "By Order"],
    price: "85,000",
    photo: { src: "/homes/the-george.jpg", alt: "The George - Single Wide manufactured home by Skyline Homes" },
  },
  {
    slug: "the-turnpike",
    name: "The Turnpike",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8808J",
    beds: 3,
    baths: 2,
    sqft: "1,600",
    tags: ["Double Wide", "By Order"],
    price: "128,000",
  },
  {
    slug: "the-bellamy",
    name: "The Bellamy",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8850",
    beds: 3,
    baths: 2,
    sqft: "1,493",
    tags: ["Double Wide", "By Order"],
    price: "121,000",
    photo: { src: "/homes/the-bellamy.jpg", alt: "The Bellamy - Double Wide manufactured home by Skyline Homes" },
  },
  {
    slug: "embrace-sunlight",
    name: "Embrace Sunlight",
    brand: "Skyline Homes",
    series: "Skyline Homes Embrace Sunlight 233",
    beds: 3,
    baths: 2,
    sqft: "1,493",
    tags: ["Double Wide", "By Order"],
    price: "124,000",
    photo: {
      src: "/homes/embrace-sunlight.jpg",
      alt: "Embrace Sunlight - Double Wide manufactured home by Skyline Homes",
    },
  },
  {
    slug: "the-sunrise",
    name: "The Sunrise",
    brand: "Skyline Homes",
    series: "Skyline Homes Embrace 2856H42A7F",
    beds: 4,
    baths: 2,
    sqft: "1,493",
    tags: ["Double Wide", "Lot Model"],
    price: "129,000",
    photo: { src: "/homes/the-sunrise.jpg", alt: "The Sunrise - Double Wide manufactured home by Skyline Homes" },
  },
  {
    slug: "the-goliath",
    name: "The Goliath",
    brand: "Skyline Homes",
    series: "Skyline Homes Genesis 9300",
    beds: 3,
    baths: 2,
    sqft: "1,680",
    tags: ["Double Wide", "By Order"],
    price: "167,000",
    photo: { src: "/homes/the-goliath.jpg", alt: "The Goliath - Double Wide manufactured home by Skyline Homes" },
  },
  {
    slug: "the-big-rich",
    name: "The Big Rich",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8901",
    beds: 4,
    baths: 2,
    sqft: "2,280",
    tags: ["Triple Wide", "By Order"],
    price: "159,000",
    photo: { src: "/homes/the-big-rich.jpg", alt: "The Big Rich - Triple Wide manufactured home by Skyline Homes" },
  },
  {
    slug: "brooks-and-dunn",
    name: "Brooks & Dunn",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8810",
    beds: 3,
    baths: 2,
    sqft: "1,144",
    tags: ["Single Wide", "By Order"],
    price: "115,000",
    photo: {
      src: "/homes/brooks-and-dunn.jpg",
      alt: "Brooks & Dunn - Single Wide manufactured home by Skyline Homes",
    },
  },
  {
    slug: "the-nitty-gritty",
    name: "The Nitty Gritty",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8853",
    beds: 3,
    baths: 2,
    sqft: "1,706",
    tags: ["Double Wide", "By Order"],
    price: "138,000",
    photo: {
      src: "/homes/the-nitty-gritty.jpg",
      alt: "The Nitty Gritty - Double Wide manufactured home by Skyline Homes",
    },
  },
  {
    slug: "the-space",
    name: "The Space",
    brand: "Skyline Homes",
    series: "Skyline Homes Embrace Series 3276H53A7E",
    beds: 5,
    baths: 3,
    sqft: "2,305",
    tags: ["Triple Wide", "Lot Model"],
    price: "170,000",
    photo: { src: "/homes/the-space.jpg", alt: "The Space - Triple Wide manufactured home by Skyline Homes" },
  },
  {
    slug: "the-muskadine",
    name: "The Muskadine",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8429",
    beds: 3,
    baths: 2,
    sqft: "1,120",
    tags: ["Double Wide", "By Order"],
    price: "112,000",
    photo: {
      src: "/homes/the-muskadine.jpg",
      alt: "The Muskadine - Double Wide manufactured home by Skyline Homes",
    },
  },
  {
    slug: "the-madi",
    name: "The Madi",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8452",
    beds: 3,
    baths: 2,
    sqft: "1,306",
    tags: ["Double Wide", "By Order"],
    price: "120,000",
    photo: { src: "/homes/the-madi.jpg", alt: "The Madi - Double Wide manufactured home by Skyline Homes" },
  },
  {
    slug: "the-eden",
    name: "The Eden",
    brand: "Skyline Homes",
    series: "Skyline Homes Genesis 9921A",
    beds: 3,
    baths: 2,
    sqft: "1,386",
    tags: ["Double Wide", "By Order"],
    price: "158,000",
    photo: { src: "/homes/the-eden.jpg", alt: "The Eden - Double Wide manufactured home by Skyline Homes" },
  },
  {
    slug: "the-everly",
    name: "The Everly",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8831",
    beds: 4,
    baths: 2,
    sqft: "1,493",
    tags: ["Double Wide", "By Order"],
    price: "126,000",
    photo: { src: "/homes/the-everly.jpg", alt: "The Everly - Double Wide manufactured home by Skyline Homes" },
  },
  {
    slug: "the-zion",
    name: "The Zion",
    brand: "Skyline Homes",
    series: "Skyline Homes Genesis 9302",
    beds: 3,
    baths: 2,
    sqft: "1,670",
    tags: ["Double Wide", "Lot Model"],
    price: "170,000",
    photo: { src: "/homes/the-zion.jpg", alt: "The Zion - Double Wide manufactured home by Skyline Homes" },
  },
  {
    slug: "the-dixie",
    name: "The Dixie",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8801",
    beds: 3,
    baths: 2,
    sqft: "1,456",
    tags: ["Double Wide", "By Order"],
    price: "117,000",
    photo: { src: "/homes/the-dixie.jpg", alt: "The Dixie - Double Wide manufactured home by Skyline Homes" },
  },
  {
    slug: "the-montgomery",
    name: "The Montgomery",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8862",
    beds: 3,
    baths: 2,
    sqft: "1,173",
    tags: ["Double Wide", "Lot Model"],
    price: "89,900",
    photo: {
      src: "/homes/the-montgomery.jpg",
      alt: "The Montgomery - Double Wide manufactured home by Skyline Homes",
    },
  },
  {
    slug: "the-conway",
    name: "The Conway",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8732AJ",
    beds: 2,
    baths: 2,
    sqft: "910",
    tags: ["Single Wide", "By Order"],
    price: "88,000",
    photo: { src: "/homes/the-conway.jpg", alt: "The Conway - Single Wide manufactured home by Skyline Homes" },
  },
  {
    slug: "the-loretta",
    name: "The Loretta",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8310",
    beds: 3,
    baths: 2,
    sqft: "880",
    tags: ["Single Wide", "By Order"],
    price: "79,000",
    photo: { src: "/homes/the-loretta.jpg", alt: "The Loretta - Single Wide manufactured home by Skyline Homes" },
  },
  {
    slug: "the-garth",
    name: "The Garth",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8790AK",
    beds: 3,
    baths: 2,
    sqft: "1,152",
    tags: ["Single Wide", "By Order"],
    price: "95,000",
  },
  {
    slug: "contemporary-cabin-a700",
    name: "Contemporary Cabin A700",
    brand: "Skyline Homes",
    series: "Skyline Homes Contemporary Cabin A700",
    beds: 1,
    baths: 1,
    sqft: "637",
    tags: ["Tiny Home", "By Order"],
    price: "86,000",
    photo: {
      src: "/homes/contemporary-cabin-a700.jpg",
      alt: "Contemporary Cabin A700 - Tiny Home manufactured home by Skyline Homes",
    },
  },
  {
    slug: "the-patsy",
    name: "The Patsy",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8313AJ",
    beds: 2,
    baths: 2,
    sqft: "694",
    tags: ["Tiny Home", "By Order"],
    price: "71,000",
    photo: { src: "/homes/the-patsy.jpg", alt: "The Patsy - Tiny Home manufactured home by Skyline Homes" },
  },
  {
    slug: "the-reba",
    name: "The Reba",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8719",
    beds: 2,
    baths: 2,
    sqft: "868",
    tags: ["Single Wide", "Lot Model"],
    price: "74,000",
    photo: { src: "/homes/the-reba.jpg", alt: "The Reba - Single Wide manufactured home by Skyline Homes" },
  },
  {
    slug: "the-willie",
    name: "The Willie",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8311",
    beds: 3,
    baths: 2,
    sqft: "1,013",
    tags: ["Single Wide", "By Order"],
    price: "83,000",
  },
  {
    slug: "the-martina",
    name: "The Martina",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8786AK",
    beds: 3,
    baths: 2,
    sqft: "1,152",
    tags: ["Single Wide", "By Order"],
    price: "96,000",
  },
  {
    slug: "simplicity-2",
    name: "Simplicity 2",
    brand: "Skyline Homes",
    series: "Skyline Homes Embrace 1676H32A7H",
    beds: 3,
    baths: 2,
    sqft: "1,153",
    tags: ["Single Wide", "By Order"],
    price: "97,000",
  },
  {
    slug: "the-tammy",
    name: "The Tammy",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8704AJ",
    beds: 3,
    baths: 2,
    sqft: "1,147",
    tags: ["Single Wide", "By Order"],
    price: "92,000",
  },
  {
    slug: "the-waylon",
    name: "The Waylon",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8705",
    beds: 3,
    baths: 2,
    sqft: "1,071",
    tags: ["Single Wide", "By Order"],
    price: "91,000",
  },
  {
    slug: "simplicity-1",
    name: "Simplicity 1",
    brand: "Skyline Homes",
    series: "Skyline Homes Embrace 1668H32A7H",
    beds: 3,
    baths: 2,
    sqft: "1,031",
    tags: ["Single Wide", "By Order"],
    price: "93,000",
  },
  {
    slug: "the-hank",
    name: "The Hank",
    brand: "Skyline Homes",
    series: "Skyline Homes Prairie Dune 8312",
    beds: 1,
    baths: 1,
    sqft: "533",
    tags: ["Tiny Home", "Arriving"],
    price: "58,000",
    photo: { src: "/homes/the-hank.jpg", alt: "The Hank - Tiny Home manufactured home by Skyline Homes" },
  },
];

export function parsePriceValue(price: string): number | null {
  const digits = price.replace(/[^0-9]/g, "");
  return digits ? Number(digits) : null;
}

export function parseSqftValue(sqft: string): number | null {
  const digits = sqft.replace(/[^0-9]/g, "");
  return digits ? Number(digits) : null;
}

export const homeTypes = [
  { label: "Tiny Home", min: 0, max: 799 },
  { label: "Single Wide", min: 800, max: 1_199 },
  { label: "Double Wide", min: 1_200, max: 1_999 },
  { label: "Triple Wide", min: 2_000, max: Infinity },
] as const;

export type HomeTypeLabel = (typeof homeTypes)[number]["label"];
